import React from 'react';
import { motion } from 'framer-motion';
import { FaGavel, FaFileContract, FaExclamationTriangle } from 'react-icons/fa';

const TermsPage = () => {
    return (
        <>
            {/* <Navbar /> */}
            <div className="min-h-screen bg-gray-50 text-gray-800 font-sans">
                <div className="max-w-4xl mx-auto px-4 py-8 md:px-6 md:py-12">

                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="bg-white rounded-2xl shadow-xl p-6 md:p-12 border-t-8 border-indigo-900"
                    >
                        <div className="text-center mb-8 md:mb-12">
                            <FaGavel className="mx-auto text-4xl md:text-5xl text-indigo-900 mb-4" />
                            <h1 className="text-2xl md:text-4xl font-extrabold text-gray-900 tracking-tight">Terms of Service</h1>
                            <p className="text-gray-500 mt-2 text-sm md:text-base">Effective Date: January 1, 2025</p>
                        </div>

                        <div className="prose prose-base md:prose-lg text-gray-700 max-w-none">

                            <h2 className="flex items-center gap-2 text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">
                                <FaFileContract className="text-indigo-700 flex-shrink-0" /> 1. Introduction & Acceptance
                            </h2>
                            <p>
                                Welcome to <strong>LexAI Portal</strong> ("we," "our," or "us"). By accessing or using our AI-powered legal assistance platform,
                                you ("User," "Counsel," or "Client") agree to be bound by these Terms of Service ("Terms") strictly in accordance with the
                                <strong>Information Technology Act, 2000</strong>, and applicable Indian laws. If you do not agree, strictly do not use our services.
                            </p>

                            <h2 className="flex items-center gap-2 text-xl md:text-2xl font-bold text-gray-900 mt-8 mb-4">
                                <FaExclamationTriangle className="text-red-600 flex-shrink-0" /> 2. Disclaimer: AI is Not a Lawyer
                            </h2>
                            <div className="bg-red-50 border-l-4 border-red-600 p-4 rounded-r mb-6">
                                <p className="font-bold text-red-800 mb-2 text-sm md:text-base">CRITICAL LEGAL NOTICE:</p>
                                <p className="text-xs md:text-sm text-red-700">
                                    LexAI is an Artificial Intelligence tool designed to assist legal professionals and individuals with research, drafting, and analysis.
                                    <strong>IT IS NOT A SUBSTITUTE FOR A HUMAN ADVOCATE.</strong> We do not provide "legal advice" as defined under the <strong>Advocates Act, 1961</strong>.
                                    Any output generated by LexAI (including BNS/IPC comparisons, drafts, or opinions) must be verified by a qualified legal practitioner before use in any court of law or legal proceeding.
                                </p>
                            </div>

                            <h2 className="text-lg md:text-xl font-bold text-gray-900 mt-6">3. Use of Services</h2>
                            <ul className="list-disc pl-5 space-y-2 text-sm md:text-base">
                                <li><strong>Eligibility:</strong> You must be at least 18 years old and competent to contract under the <strong>Indian Contract Act, 1872</strong>.</li>
                                <li><strong>Account Security:</strong> You are responsible for maintaining the confidentiality of your credentials (OTP/Password). Any liability arising from unauthorized access rests with you.</li>
                                <li><strong>Prohibited Conduct:</strong> You agree not to use LexAI for:
                                    <ul className="list-disc pl-5 mt-1 text-xs md:text-sm text-gray-600">
                                        <li>Generating fraudulent or forged legal documents (IPC Section 463/464).</li>
                                        <li>Misrepresenting AI-generated content as human-created work in professional filings without disclosure.</li>
                                        <li>Attempting to reverse-engineer our AI models or proprietary algorithms.</li>
                                    </ul>
                                </li>
                            </ul>

                            <h2 className="text-lg md:text-xl font-bold text-gray-900 mt-6">4. Subscription & Wallet Payments</h2>
                            <p className="text-sm md:text-base">
                                LexAI operates on a "Pay-Per-Token" or Subscription model.
                            </p>
                            <ul className="list-disc pl-5 space-y-2 text-sm md:text-base">
                                <li><strong>Wallet Balance:</strong> Credits added to your LexAI Wallet are for service usage only and are non-transferable.</li>
                                <li><strong>Refunds:</strong> Payments are generally non-refundable unless the service is unavailable for &gt;48 hours due to our fault, subject to the <strong>Consumer Protection Act, 2019</strong>.</li>
                                <li><strong>Pricing:</strong> We reserve the right to modify token consumption rates (e.g., 1 Paise/token for Gemini Ultra) with prior notice on the dashboard.</li>
                            </ul>

                            <h2 className="text-lg md:text-xl font-bold text-gray-900 mt-6">5. Intellectual Property Rights (IPR)</h2>
                            <ul className="list-disc pl-5 space-y-2 text-sm md:text-base">
                                <li><strong>Platform Rights:</strong> The LexAI code, branding, and AI fine-tuning data are our exclusive intellectual property protected under the <strong>Copyright Act, 1957</strong> and <strong>Trade Marks Act, 1999</strong>.</li>
                                <li><strong>User Generations:</strong> You retain ownership of the specific legal drafts and queries you create using LexAI. However, you grant us a limited license to process this data solely for generating your response.</li>
                            </ul>

                            <h2 className="text-lg md:text-xl font-bold text-gray-900 mt-6">6. Limitation of Liability</h2>
                            <p className="text-sm md:text-base">
                                To the maximum extent permitted by Indian Law:
                            </p>
                            <ul className="list-disc pl-5 space-y-2 text-sm md:text-base">
                                <li>We expressly disclaim liability for any errors, hallucinations, or outdated statutes (e.g., confusion between BNS 2023 and IPC 1860) in the AI output.</li>
                                <li>We shall not be liable for any indirect, incidental, or consequential damages (including loss of cases or professional reputation) arising from your reliance on LexAI.</li>
                                <li>Our total liability shall not exceed the amount paid by you in the last 30 days.</li>
                            </ul>

                            <h2 className="text-lg md:text-xl font-bold text-gray-900 mt-6">7. Data Protection</h2>
                            <p className="text-sm md:text-base">
                                We process your data in compliance with the <strong>Digital Personal Data Protection (DPDP) Act, 2023</strong>. Please refer to our <a href="/privacy" className="text-indigo-600 underline">Privacy Policy</a> for details on how we handle Sensitive Personal Data (SPD).
                            </p>

                            <h2 className="text-lg md:text-xl font-bold text-gray-900 mt-6">8. Dispute Resolution</h2>
                            <p className="text-sm md:text-base">
                                Any disputes shall be subject to the exclusive jurisdiction of the courts in <strong>New Delhi, India</strong>. All disputes shall be resolved via arbitration under the <strong>Arbitration and Conciliation Act, 1996</strong> by a sole arbitrator appointed by LexAI.
                            </p>

                        </div>

                        <div className="mt-8 md:mt-12 pt-6 md:pt-8 border-t border-gray-200 text-center">
                            <p className="text-gray-500 italic text-xs md:text-sm">
                                By continuing to use LexAI, you acknowledge that you have read, understood, and agreed to these Terms.
                            </p>
                            <button
                                onClick={() => window.history.back()}
                                className="mt-6 w-full md:w-auto px-8 py-3 bg-indigo-900 text-white rounded-lg hover:bg-indigo-800 transition shadow-lg font-semibold text-sm md:text-base"
                            >
                                I Acknowledge & Return
                            </button>
                        </div>

                    </motion.div>
                </div>
            </div>
            {/* <Footer /> */}
        </>
    );
};

export default TermsPage;
